// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	comment "github.com/Yra-A/Douyin_Simple_Demo/cmd/api/biz/router/comment"
	favorite "github.com/Yra-A/Douyin_Simple_Demo/cmd/api/biz/router/favorite"
	feed "github.com/Yra-A/Douyin_Simple_Demo/cmd/api/biz/router/feed"
	message "github.com/Yra-A/Douyin_Simple_Demo/cmd/api/biz/router/message"
	publish "github.com/Yra-A/Douyin_Simple_Demo/cmd/api/biz/router/publish"
	relation "github.com/Yra-A/Douyin_Simple_Demo/cmd/api/biz/router/relation"
	user "github.com/Yra-A/Douyin_Simple_Demo/cmd/api/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	user.Register(r)

	publish.Register(r)

	message.Register(r)

	feed.Register(r)

	favorite.Register(r)

	relation.Register(r)

	comment.Register(r)

	api.Register(r)
}
