version: '3'

services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    volumes:
      - ./pkg/configs/sql:/docker-entrypoint-initdb.d
    ports:
      - "18000:3306"
    networks:
      - default
    environment:
      - MYSQL_DATABASE=test_douyin
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_RANDOM_ROOT_PASSWORD="no"
    restart: always
    profiles:
      - dev

  minio:
    image: quay.io/minio/minio:latest
    container_name: tiktok_minio
    ports:
      - "18001:9000"
      - "18002:9001"
    environment:
      MINIO_ACCESS_KEY: douyin
      MINIO_SECRET_KEY: douyin111
    volumes:
      - ./pkg/data/minio/:/data
      - ./pkg/configs/minio/:/root/.minio
    command: server --console-address ':9001' /data
    privileged: true
    restart: always
    profiles:
      - dev

  etcd:
    image: 'quay.io/coreos/etcd:v3.5.9'
    container_name: etcd
    restart: always
    ports:
      - 2379:2379
    networks:
      - default
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCDCTL_API=3
    profiles:
        - dev
