server:
	cd ../.. && kitex -module github.com/Yra-A/Douyin_Simple_Demo idl/publish.thrift
	kitex -module github.com/Yra-A/Douyin_Simple_Demo -service FeedService -use github.com/Yra-A/Douyin_Simple_Demo/kitex_gen ../../idl/publish.thrift