update_all:
	hz update -idl ../../idl/comment.thrift
	hz update -idl ../../idl/relation.thrift
	hz update -idl ../../idl/favorite.thrift
	hz update -idl ../../idl/feed.thrift
	hz update -idl ../../idl/message.thrift
	hz update -idl ../../idl/publish.thrift
	hz update -idl ../../idl/relation.thrift
	hz update -idl ../../idl/user.thrift

update_comment:
	hz update -idl ../../idl/comment.thrift

update_relation:
	hz update -idl ../../idl/relation.thrift

update_favorite:
	hz update -idl ../../idl/favorite.thrift

update_feed:
	hz update -idl ../../idl/feed.thrift

update_message:
	hz update -idl ../../idl/message.thrift

update_publish:
	hz update -idl ../../idl/publish.thrift

update_user:
	hz update -idl ../../idl/user.thrift