// Code generated by hertz generator.

package user

import (
  "context"
  "github.com/cloudwego/hertz/pkg/app"
)

// UserRegister .
// @router /douyin/user/register/ [POST]
func UserRegister(ctx context.Context, c *app.RequestContext) {

}

// UserLogin .
// @router /douyin/user/login/ [POST]
func UserLogin(ctx context.Context, c *app.RequestContext) {

}

// UserLogin .
// @router /douyin/user/ [GET]
func UserInfo(ctx context.Context, c *app.RequestContext) {

}
